[package]
name = "lockbook"
version = "0.1.0"
authors = ["parth"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lockbook_core = { path = "../../core" }
structopt = "0.3.13"
uuid = "0.8"
serde_json = "1.0.44"

