version: '3'

services:
  filesdb:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    env_file:
      - containers/test.env
    entrypoint: /bin/sh -c 'MINIO_REGION_NAME=$$FILES_DB_REGION /usr/bin/minio server /data'
  config_files_db:
    image: minio/mc:RELEASE.2020-05-16T01-44-37Z
    env_file:
      - containers/test.env
    depends_on:
      - filesdb
    entrypoint: >
      /bin/sh -c '\
        while ! nc -z $$FILES_DB_HOST $$FILES_DB_PORT; do echo "$$FILES_DB_HOST Waiting for Minio to start..." && sleep 0.2; done; \
        /usr/bin/mc config host add filesdb $$FILES_DB_SCHEME://$$FILES_DB_HOST:$$FILES_DB_PORT $$FILES_DB_ACCESS_KEY $$FILES_DB_SECRET_KEY && \
        /usr/bin/mc mb --region=$$FILES_DB_REGION filesdb/$$FILES_DB_BUCKET && \
        /usr/bin/mc policy set public filesdb/$$FILES_DB_BUCKET \
      '
