name: client
description: A secure notebook

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pointycastle: ^1.0.2    # For asymmetric crypto
  http: ^0.12.0+3         # Networking
  crypto: 2.1.3           # For SHA
  path_provider: ^1.5.1   # For platform aware app directories
  zefyr: ^0.9.0           # For Markdown
  quill_delta: ^1.0.0     # MD deltas
  sqflite: ^1.2.0         # For persisting
  uuid: 2.0.4             # For UUID generation
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
