[package]
name = "lockbook_core"
version = "2.1.5"
authors = ["Parth <parth@mehrotra.me>", "Raayan <raayan@raayanpillai.com>", "Travis <t.vanderstad@gmail.com>"]
edition = "2018"
description = "The functional components of the iOS and Android lockbook clients."
license = "BSD-3-Clause"

[lib]
name = "lockbook_core"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
reqwest = "0.9.24"
rusqlite = { version = "0.21.0", features = ["bundled"] }
openssl = { version = "0.10", features = ["vendored"] }
base64 = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
uuid = { version = "0.8.1", features = ["v4"] }
