[package]
name = "lockbook-server"
version = "0.1.0"
authors = ["Parth <parth@mehrotra.me>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
rocket = "0.4.2"
postgres = "0.17.0"
postgres-openssl = "0.3.0"
openssl = { version = "0.10", features = ["vendored"] }
tokio-postgres = "0.5.1"
rust-s3 = "0.18.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
lockbook_core = "3.1.5"
