name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
  pull_request:
    branches: [ master ]

jobs:
  Core:
    runs-on: ubuntu-latest
    env:
      working-directory: ./core
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      BRANCH: ${{ github.head_ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: docker login docker.pkg.github.com -u Github_Actions -p $GH_TOKEN
    - name: Pull older image for cache
      run: make core_pull
    - name: Build container
      run: make core_cached
    - name: Lint
      run: make core_lint
    - name: Compile and run tests
      run: make core_test
    - name: Check Formatting
      run: make core_fmt
    - name: Publish container
      run: make core_push
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Build Core - ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: always()
  Server:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      BRANCH: ${{ github.head_ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: docker login docker.pkg.github.com -u Github_Actions -p $GH_TOKEN
    - name: Pull older image for cache
      run: make server_pull
    - name: Build container
      run: make server_cached
    - name: Lint
      run: make server_lint
    - name: Compile and run tests
      run: make server_test
    - name: Check Formatting
      run: make server_fmt
    - name: Publish container
      run: make server_push
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Build Server - ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: always()
      