name: Integration

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
  pull_request:
    branches: [ master ]

jobs:
  ReallyClean:
    runs-on: [self-hosted, dockerized]
    steps:
    - name: Clean
      run: make exorcise
