name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Core:
    runs-on: ubuntu-latest
    env:
      working-directory: ./core
      LOCKBOOK_API_LOCATION: http://lockbook.app:8000
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Lint
      run: cargo fmt -- --check -l
      working-directory: ${{env.working-directory}}
    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: build
        args: --manifest-path core/Cargo.toml
    - name: Test
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: test
        args: --manifest-path core/Cargo.toml --verbose
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Build Core - ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: always()
