name: Lockbook

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Server:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Lint
      run: cargo fmt --quiet -- --check
      working-directory: ${{env.working-directory}}
    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
        command: build
        args: --manifest-path server/Cargo.toml
