name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Server:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo fmt --quiet -- --check
