name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      run: |
        cd core
        cargo install cargo-lipo
        rustup target add aarch64-apple-ios x86_64-apple-ios
        ./build_for_xcode.sh -f
        cd ../clients/ios
        xcodebuild -project ios_client.xcodeproj -allowProvisioningUpdates CODE_SIGNING_ALLOWED=NO
